version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8000:80
    env_file: wp.env
    volumes:
      - wordpress:/var/www/html
      - type: bind
        source: ./alfredciii_wp_theme
        target: /var/www/html/wp-content/themes/alfredciii_wp_theme
        read_only: true

  db:
    image: mysql:5.7
    restart: always
    env_file: db.env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
